#设置端口还有前缀
server:
  port: 8081
#  servlet:
#   context-path: /springboot

spring:
  thymeleaf:
    cache: false #   关闭缓存
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloudorder?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.99.171.139
    password: 123456
    port: 6379
    database: 6
  rabbitmq:
    host: 47.99.171.139
  rabbitmq:
    host: 47.99.171.139
    port: 5672
    username: guest
    password: guest
  application:
    name: order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka

logging:
  level:
    org.springframework: info #org.springframework用到的是普通级别通知
    net.seehope: debug # net.seehope用到的是调试级别通知
mybatis:
  mapper-locations:
    - classpath*:mappers/**/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl#开启日志框架
    cache-enabled: true
